version: "3"
services:
  node-app:
    container_name: express-nodejs
    build: .
    volumes:
      - ./src:/app/src:ro # When using bind mounts, you can specify the exact location on your host machine that should be linked to the container
    ports:
      - "4000:4000" 
    env_file:
      - ./.env
    depends_on:
      - mongo    # Node app depends on MongoDB to be available
      - redis    # Node app depends on Redis to be available
    
  

  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: asmaa
    volumes:
      - mongo_db:/data/db


# UI tool for mongo database 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: asmaa
      ME_CONFIG_MONGODB_URL: mongodb://root:asmaa@mongo:27017/
      ME_CONFIG_BASICAUTH: true
    depends_on:
      - mongo

  redis:
    image: redis
    depends_on:
      - mongo 


# forwarding client requests to backend servers (such as application servers or databases)
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - node-app # use the container name as the hostname to access the app container


volumes:
  mongo_db: